### ISSUE TITLE
Site goes behind Status bar

### ISSUE THREAD

**Issue by idiosyncraticee** [idiosyncraticee/SimpleApp2#1]
The status bar at the very top with 'Carrier' etc, has the webpage showing in it when scrolling down the page.  If I follow a link it doesn't show up behind.  I think this has something to do with the navigation bar.

**Comment by hoangtuanfithou** [comment]
@idiosyncraticee :+1: ok I checking all issues.

**Comment by idiosyncraticee** [comment]
Hi Tuan,

What do you think?

      -Chris

On Fri, Jul 10, 2015 at 9:22 PM, Nguyen Hoang Tuan <notifications@github.com

**Comment by hoangtuanfithou** [comment]
Hi Chris
I resolved some of the issues, and testing them again.
The others issues I will to finish all in Monday.
Br

**Comment by idiosyncraticee** [comment]
Hi Tuan,

Sounds good.  Should we agree on a price before you do too much more work?

      -Chris
